services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: aoropeza
      POSTGRES_DB: piscineds
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: