version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: aoropeza
      POSTGRES_DB: piscineds
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: